# Generated by Django 4.2.29 on 2026-04-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialrecord",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
